
version: '3.4'

services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: db
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=P@ssw0rd
